export const RECEIVE_WEATHER = 'RECEIVE_WEATHER';
export const GET_CURRENT_WEATHER = 'GET_CURRENT_WEATHER';

export const RECEIVE_FORECAST = 'RECEIVE_FORECAST';
export const GET_FORECAST = 'GET_FORECAST';

export const CHANGE_CITY = 'CHANGE_CITY';

export const CHANGE_SCALE = 'CHANGE_SCALE';